### ISSUE TITLE
Teacher's Review for Week 4

### ISSUE THREAD

**Issue by jeankim05** [jeankim05/flask_portfolio#27]

**Comment by suneelanaidu** [comment]
Teacher's Review for week 4:
1. Good job trying to get the requirements done.  You need to also work as a team and be in synch with each other.
2. Follow canvas requirements each week closely and show tangibles for each. 
3. Keep scrum board up-to-date, add new tasks as your PBL requires and move done items to Done column. Keep Time Boxed section of README and plans for work updated at all times.
4. Your main web page must start looking like your own "unique idea" page and each About Us page can have more features/content added by the individual.
5. Continue Learning/Involvement in PBL and mini labs and it will help you for the final AP Test.
