### ISSUE TITLE
Scrum / Pair Activity - Alex and Allie

### ISSUE THREAD

**Issue by jeankim05** [jeankim05/flask_portfolio#32]
- [x] Write about OO and TO Roles in Journal and incorporate a summary
- [x] 3.1 Notes and Work in Journal
- [x] 3.2 Notes and Work in Journal

**Comment by xiaoa0** [comment]
[Journal with tangibles](https://docs.google.com/document/d/1M3uMIrhcwQYRoes55MLlfpXWSMjIIvjR96f8v07PCUU/edit?usp=sharing)
