### ISSUE TITLE
Week 8 Class Presentation Review

### ISSUE THREAD

**Issue by jeankim05** [jeankim05/flask_portfolio#55]

**Comment by RohanG326** [comment]
3 things we liked:
-Really liked the sports information tab
-Enjoyed the personalization and how you based the theme off of interests you have
-The apparel section that took us to the specific link was good
1 improvement:
-A huge thing was the formatting. I think working on formatting each page and making it look cleaner would make it look a lot more professional

**Comment by samayass** [comment]
Highlights:
Great functionality
Color choices match the theme and are well-chosen
Api idea was a good choice to integrate

Improvement:
Work on the design to make it more clean and modern.

**Comment by MadCacti** [comment]
Idea of API usage was creative for the website
Wireframe well planned and organized

Improvement:
Use css to style your website, make it look nicer
